#! configuration/base.yaml
application:
  # You need to set the `APP_APPLICATION__HMAC_SECRET` environment
  # variable on Digital Ocean as well for production!
  hmac_secret: "github1-test2-password4-non3-compromising5-zorro1991-watermelon1015"
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  # New value!
  # We are only setting the development value,
  # we'll deal with the production token outside of version control
  # (given that it's a sensitive secret!)
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
redis_uri: "redis://127.0.0.1:6379"