#! configuration/base.yaml
application:
  # You need to set the `APP_APPLICATION__HMAC_SECRET` environment
  # variable on Digital Ocean as well for production!
  hmac_secret: "try-nice-get-twice-try-thrice-no-dice-even4-dumbl3d0re-s3cr37-g4l0r3"
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  # New value!
  # We are only setting the development value,
  # we'll deal with the production token outside of version control
  # (given that it's a sensitive secret!)
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000